/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiQualificationsTeacherApplicationsRouteImport } from './routes/api/qualifications.teacher-applications'
import { Route as ApiPublicAuthLogRouteImport } from './routes/api/public/auth-log'
import { Route as ApiAuthRegisterRouteImport } from './routes/api/auth.register'
import { Route as ApiAuthMeRouteImport } from './routes/api/auth.me'
import { Route as ApiAuthLoginRouteImport } from './routes/api/auth.login'
import { Route as ApiAdminTeacherApplicationsRouteImport } from './routes/api/admin.teacher-applications'
import { Route as ApiUsersMeProfileRouteImport } from './routes/api/users.me.profile'
import { Route as ApiAdminUsersIdRouteImport } from './routes/api/admin.users.$id'
import { Route as ApiAdminTeacherApplicationsIdRouteImport } from './routes/api/admin.teacher-applications.$id'
import { Route as ApiAdminAuthLoginRouteImport } from './routes/api/admin.auth.login'

const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiQualificationsTeacherApplicationsRoute =
  ApiQualificationsTeacherApplicationsRouteImport.update({
    id: '/api/qualifications/teacher-applications',
    path: '/api/qualifications/teacher-applications',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicAuthLogRoute = ApiPublicAuthLogRouteImport.update({
  id: '/api/public/auth-log',
  path: '/api/public/auth-log',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthRegisterRoute = ApiAuthRegisterRouteImport.update({
  id: '/api/auth/register',
  path: '/api/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthMeRoute = ApiAuthMeRouteImport.update({
  id: '/api/auth/me',
  path: '/api/auth/me',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLoginRoute = ApiAuthLoginRouteImport.update({
  id: '/api/auth/login',
  path: '/api/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminTeacherApplicationsRoute =
  ApiAdminTeacherApplicationsRouteImport.update({
    id: '/api/admin/teacher-applications',
    path: '/api/admin/teacher-applications',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiUsersMeProfileRoute = ApiUsersMeProfileRouteImport.update({
  id: '/api/users/me/profile',
  path: '/api/users/me/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminUsersIdRoute = ApiAdminUsersIdRouteImport.update({
  id: '/api/admin/users/$id',
  path: '/api/admin/users/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminTeacherApplicationsIdRoute =
  ApiAdminTeacherApplicationsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => ApiAdminTeacherApplicationsRoute,
  } as any)
const ApiAdminAuthLoginRoute = ApiAdminAuthLoginRouteImport.update({
  id: '/api/admin/auth/login',
  path: '/api/admin/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/api/admin/teacher-applications': typeof ApiAdminTeacherApplicationsRouteWithChildren
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/me': typeof ApiAuthMeRoute
  '/api/auth/register': typeof ApiAuthRegisterRoute
  '/api/public/auth-log': typeof ApiPublicAuthLogRoute
  '/api/qualifications/teacher-applications': typeof ApiQualificationsTeacherApplicationsRoute
  '/api/admin/auth/login': typeof ApiAdminAuthLoginRoute
  '/api/admin/teacher-applications/$id': typeof ApiAdminTeacherApplicationsIdRoute
  '/api/admin/users/$id': typeof ApiAdminUsersIdRoute
  '/api/users/me/profile': typeof ApiUsersMeProfileRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/api/admin/teacher-applications': typeof ApiAdminTeacherApplicationsRouteWithChildren
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/me': typeof ApiAuthMeRoute
  '/api/auth/register': typeof ApiAuthRegisterRoute
  '/api/public/auth-log': typeof ApiPublicAuthLogRoute
  '/api/qualifications/teacher-applications': typeof ApiQualificationsTeacherApplicationsRoute
  '/api/admin/auth/login': typeof ApiAdminAuthLoginRoute
  '/api/admin/teacher-applications/$id': typeof ApiAdminTeacherApplicationsIdRoute
  '/api/admin/users/$id': typeof ApiAdminUsersIdRoute
  '/api/users/me/profile': typeof ApiUsersMeProfileRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/api/admin/teacher-applications': typeof ApiAdminTeacherApplicationsRouteWithChildren
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/me': typeof ApiAuthMeRoute
  '/api/auth/register': typeof ApiAuthRegisterRoute
  '/api/public/auth-log': typeof ApiPublicAuthLogRoute
  '/api/qualifications/teacher-applications': typeof ApiQualificationsTeacherApplicationsRoute
  '/api/admin/auth/login': typeof ApiAdminAuthLoginRoute
  '/api/admin/teacher-applications/$id': typeof ApiAdminTeacherApplicationsIdRoute
  '/api/admin/users/$id': typeof ApiAdminUsersIdRoute
  '/api/users/me/profile': typeof ApiUsersMeProfileRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/api/admin/teacher-applications'
    | '/api/auth/login'
    | '/api/auth/me'
    | '/api/auth/register'
    | '/api/public/auth-log'
    | '/api/qualifications/teacher-applications'
    | '/api/admin/auth/login'
    | '/api/admin/teacher-applications/$id'
    | '/api/admin/users/$id'
    | '/api/users/me/profile'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/api/admin/teacher-applications'
    | '/api/auth/login'
    | '/api/auth/me'
    | '/api/auth/register'
    | '/api/public/auth-log'
    | '/api/qualifications/teacher-applications'
    | '/api/admin/auth/login'
    | '/api/admin/teacher-applications/$id'
    | '/api/admin/users/$id'
    | '/api/users/me/profile'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/api/admin/teacher-applications'
    | '/api/auth/login'
    | '/api/auth/me'
    | '/api/auth/register'
    | '/api/public/auth-log'
    | '/api/qualifications/teacher-applications'
    | '/api/admin/auth/login'
    | '/api/admin/teacher-applications/$id'
    | '/api/admin/users/$id'
    | '/api/users/me/profile'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  ApiAdminTeacherApplicationsRoute: typeof ApiAdminTeacherApplicationsRouteWithChildren
  ApiAuthLoginRoute: typeof ApiAuthLoginRoute
  ApiAuthMeRoute: typeof ApiAuthMeRoute
  ApiAuthRegisterRoute: typeof ApiAuthRegisterRoute
  ApiPublicAuthLogRoute: typeof ApiPublicAuthLogRoute
  ApiQualificationsTeacherApplicationsRoute: typeof ApiQualificationsTeacherApplicationsRoute
  ApiAdminAuthLoginRoute: typeof ApiAdminAuthLoginRoute
  ApiAdminUsersIdRoute: typeof ApiAdminUsersIdRoute
  ApiUsersMeProfileRoute: typeof ApiUsersMeProfileRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/qualifications/teacher-applications': {
      id: '/api/qualifications/teacher-applications'
      path: '/api/qualifications/teacher-applications'
      fullPath: '/api/qualifications/teacher-applications'
      preLoaderRoute: typeof ApiQualificationsTeacherApplicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/auth-log': {
      id: '/api/public/auth-log'
      path: '/api/public/auth-log'
      fullPath: '/api/public/auth-log'
      preLoaderRoute: typeof ApiPublicAuthLogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/register': {
      id: '/api/auth/register'
      path: '/api/auth/register'
      fullPath: '/api/auth/register'
      preLoaderRoute: typeof ApiAuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/me': {
      id: '/api/auth/me'
      path: '/api/auth/me'
      fullPath: '/api/auth/me'
      preLoaderRoute: typeof ApiAuthMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/login': {
      id: '/api/auth/login'
      path: '/api/auth/login'
      fullPath: '/api/auth/login'
      preLoaderRoute: typeof ApiAuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/teacher-applications': {
      id: '/api/admin/teacher-applications'
      path: '/api/admin/teacher-applications'
      fullPath: '/api/admin/teacher-applications'
      preLoaderRoute: typeof ApiAdminTeacherApplicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/users/me/profile': {
      id: '/api/users/me/profile'
      path: '/api/users/me/profile'
      fullPath: '/api/users/me/profile'
      preLoaderRoute: typeof ApiUsersMeProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/users/$id': {
      id: '/api/admin/users/$id'
      path: '/api/admin/users/$id'
      fullPath: '/api/admin/users/$id'
      preLoaderRoute: typeof ApiAdminUsersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/teacher-applications/$id': {
      id: '/api/admin/teacher-applications/$id'
      path: '/$id'
      fullPath: '/api/admin/teacher-applications/$id'
      preLoaderRoute: typeof ApiAdminTeacherApplicationsIdRouteImport
      parentRoute: typeof ApiAdminTeacherApplicationsRoute
    }
    '/api/admin/auth/login': {
      id: '/api/admin/auth/login'
      path: '/api/admin/auth/login'
      fullPath: '/api/admin/auth/login'
      preLoaderRoute: typeof ApiAdminAuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ApiAdminTeacherApplicationsRouteChildren {
  ApiAdminTeacherApplicationsIdRoute: typeof ApiAdminTeacherApplicationsIdRoute
}

const ApiAdminTeacherApplicationsRouteChildren: ApiAdminTeacherApplicationsRouteChildren =
  {
    ApiAdminTeacherApplicationsIdRoute: ApiAdminTeacherApplicationsIdRoute,
  }

const ApiAdminTeacherApplicationsRouteWithChildren =
  ApiAdminTeacherApplicationsRoute._addFileChildren(
    ApiAdminTeacherApplicationsRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  ApiAdminTeacherApplicationsRoute:
    ApiAdminTeacherApplicationsRouteWithChildren,
  ApiAuthLoginRoute: ApiAuthLoginRoute,
  ApiAuthMeRoute: ApiAuthMeRoute,
  ApiAuthRegisterRoute: ApiAuthRegisterRoute,
  ApiPublicAuthLogRoute: ApiPublicAuthLogRoute,
  ApiQualificationsTeacherApplicationsRoute:
    ApiQualificationsTeacherApplicationsRoute,
  ApiAdminAuthLoginRoute: ApiAdminAuthLoginRoute,
  ApiAdminUsersIdRoute: ApiAdminUsersIdRoute,
  ApiUsersMeProfileRoute: ApiUsersMeProfileRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
